# Generated by Django 6.0.5 on 2026-05-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('entered_time', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='writer', related_query_name='Query_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
